### ISSUE TITLE
Status of spectate_mode_minimal_ui and pow2_tex doesn't persist between game loads

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#107]
The status of the "spectate_mode_minimal_ui" and "pow2_tex" should persist when exiting and relaunching the game. Currently, they do not, so they must be re-entered every session you wish for them to be active.

**Comment by rafalh** [comment]
"pow2_tex" is totally an advanced flag that I don't want people to use for a longer span of time. It actually restores RF bug that used to happen when graphics card were unable to render non-pow2 textures. Allowing people to permanently enable RF bugs like this is not something I'd like to see.
"spectate_mode_minimal_ui" is less controversial but I don't see it used often. If more people would complain about it not being persisted - sure. But if it's just you asking for the sake of persisting state of every command I disagree. I want to persist only things that are useful in the long-term.
