### ISSUE TITLE
Spectate flickering bug in 1.6.0-beta

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#11]
See video of issue here from today's game night: https://www.youtube.com/watch?v=d6X74NS7-SU

Haven't been able to nail down a specific cause - possibly related to spectating a player who switches to the rocket, though I haven't been able to replicate it consistently with only that.

**Comment by rafalh** [comment]
Fixed by commit d9abd3c1941f5afed2bfe6c03d79bf9ba1b3dcd0
