### ISSUE TITLE
"EAX Sound" applying 3D audio to everything when it shouldn't.

### ISSUE THREAD

**Issue by fatcatonmars** [rafalh/dashfaction#110]
Menu sounds, interaction noises, player gunshots, voiced radio dialogue, etc, when facing in different directions cause the 3D effect to be applied even when the sounds should be static.

**Comment by rafalh** [comment]
I never experienced such issue. Could you please record some video showing the issue?
What is your operating system?

**Comment by fatcatonmars** [comment]
Video: https://streamable.com/xbb8fc

![image](https://user-images.githubusercontent.com/31595440/119227648-51f1a480-bae5-11eb-9202-a0aee89cec45.png)

Vanilla install and Dash Faction 1.6.1
