### ISSUE TITLE
Suggestion: Allow usage of "lightmap only" rendering option in multiplayer

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#111]
I would suggest that allowing usage of "debug lightmap" in multiplayer for enhanced visibility would be a really great option for helping players see what they're shooting at, especially in competitive multiplayer games. I'm specifically requesting this because I've heard from multiple players particularly in CTF having trouble seeing players because of the textures behind them (usually the red team due to RF having LOADS of red rock textures). I don't see a downside to allowing players to use lightmap only mode, and it would solve any such issues with visibility and ensure one team doesn't have an advantage over the other because they camouflage better into the environment. 

This could be either via its debug command (same as "debug network" is allowed in multiplayer) or via a new command if you thought that would make more sense ("lightmaps_only" or something like that?).

I don't think allowing this in all cases is of concern, but if you were worried about Dash 1.7.0+ players having a potential advantage or anything, you could consider only allowing clients to use it when $DF Anticheat Level is >=1, which would ensure that practically all players have the option available to them (ie. are running Dash 1.7.0+).

**Comment by rafalh** [comment]
I don't like this idea. I don't want to reduce graphics quality for the sake of competitiveness. Maybe in special server controlled mode (aka Match Mode) but I'm not planning to work on it anytime soon.
