### ISSUE TITLE
Implement autosave system

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#124]
This is based on a suggestion on the Discord from MysticaL-AceR

One of the primary pain points for many players picking RF up today is the lack of autosave or checkpoint-based savegame system. Requiring manual saves can result in a lot of frustration if you forget to save for a while, then die and have to redo large portions of the game. I've had people tell me that they've quit the game after that, for example, rather than replay the campaign to get back to where they were after a death. Most modern games do have some type of autosave system as well, which means people would likely expect it - in fact, many Steam/etc reviews of the game cite the lack of autosave/checkpoint system as a negative when evaluating the game.

Suggestion: After the game processes a Load_Level event, a savegame file named "autosave.svl" is automatically generated. This single file will be updated at the start of each level, so players will always have a way to return to a fairly recent savegame file when they die.

**Comment by rafalh** [comment]
This can be confusing or even annoying for players that may expect to have Quick Load function to load state saved manually by Quick Save key. What's worse it may save game in a bad state with low HP/Armor etc. But if it was saving as a different filename maybe it would be okay? What do you think?

**Comment by GooberRF** [comment]
"have Quick Load function to load state saved manually by Quick Save key."
My thought was that the autosave.svl file would function entirely separately from quick saving. There would be no hotkey to load the autosave.svl file, it would just be accessible via the Load Game menu if you wanted to use it.

Maybe a good solution could be to maintain a number of autosave files? Say autosave0.svl will always be the most recent, autosave1.svl is the second most recent, etc.

There's no reason this approach wouldn't work for custom campaigns and mods too

**Comment by tunbridgep** [comment]
> This can be confusing or even annoying for players that may expect to have Quick Load function to load state saved manually by Quick Save key. What's worse it may save game in a bad state with low HP/Armor etc. But if it was saving as a different filename maybe it would be okay? What do you think?

This is how autosaving works in most games. Autosaves are their own "slot" which ovewrites the previous autosave, completely unrelated from quick saving. Quick loading always loads the quicksave, and "reload from last save" on death loads the latest save, quicksave or not.

If you want it to work with all mods and be a simple solution, then it's easy - just make an autosave everytime a new map is loaded. Will be automatically compatible with everything.

**Comment by tunbridgep** [comment]
So the standard ways to do autosaves in games works like this:
- Maintain a separate autosave save file, autosave.svl
- Upon loading a new map, save over the previous autosave
- This is unrelated to quickloading/quicksaving.

Alternatively, maintain an autosave number in the campaign and every time you save you loop it between 0 and some max number, always saving to that slot, so

autosave0.svl, autosave1.svl etc

having to make autosave0 always be the latest one means the autosaves will keep getting renamed and it's a really complicated system. The save menu already sorts by date, so better to just loop through all the save slot numbers in a simple way.
