### ISSUE TITLE
Level/map console commands fail if the given RFL name has a . in it

### ISSUE THREAD

**Issue by natarii** [rafalh/dashfaction#139]
If the RFL name given has a . in it, the . and everything after it is ignored. Presumably this is to strip off the .rfl extension if the level name was entered with it, but this causes issues on some maps, for example `dm-disco_run_2_.1` is not possible to select via the console.

**Comment by rafalh** [comment]
I looked into the code and I see RF would have problems with such filenames in a lot of places. Such filenames shouldn't work when launching level from editor too. You cannot have dots in mesh or savegame filenames too. I'm not sure if it's worth fixing. Fixing one place would make it inconsistent and fixing it everywhere would be quite a lot of work for a little benefit.

**Comment by natarii** [comment]
Ah, if it's broken in other places then I think it's okay to leave as something mappers shouldn't do. I only encountered a few maps with . in the filename anyway.
