### ISSUE TITLE
Increase the Clutter and Entities limit for savegame files

### ISSUE THREAD

**Issue by MartianMadman** [rafalh/dashfaction#155]
Assuming that this is even possible, it would be a big relief to me since these two limits are showing to be the most problematic in my SP modding. Personally I'd like to see a 4x increase in the entity limit since level 13 in TCoO has 221 entities meaning 3x won't be enough. Level 5 exceeds the clutter limit but I think a 2x increase in the clutter limit would be enough since that limit is already kind of high.

**Comment by rafalh** [comment]
I am not planning to change the save file format which would be necessary to change the limits. It's too much work and benefits are too small.
