### ISSUE TITLE
Make putting on the lab coat require the USE key to avoid accidental stealth

### ISSUE THREAD

**Issue by tunbridgep** [rafalh/dashfaction#164]
So I used this patch for my first playthrough. I was extremely annoyed when I entered the medical facility, turned to enter a new room and BANG, suddenly I have no weapons with no way to get them back. I was not intending to go into "stealth" mode, and the medical facility is part of the game you can do in stealth or combat.

I think the game would be more forgiving for newer players (I am sure I'm not the only one who used this on their first playthrough) if going into stealth required pressing the use key. This way, we can enter the room and explore around without having our weapons suddenly removed without warning.

**Comment by MysticaL-AceR** [comment]
Im afraid the labcoat counts as an item just like weapons/ammo/armor etc. To avoid that, is by modifying the script of the entire map itself so it requires mapping work. Don't think its wise to recreate that, unless its a custom mod.

**Comment by tunbridgep** [comment]
That's a shame. Would it be worth including a "tweaks and fixes" mod alongside the patch that fixes this, adds a bit more health in locations where it makes sense (like RIGHT before the final boss) etc?

There are some janky bits.

I can understand if it's beyond scope of this mod, though.

**Comment by tunbridgep** [comment]
Doesn't this mod have the ability to change the game's code? I'm sure it wouldn't require a map mod to make this work

**Comment by tunbridgep** [comment]
Maybe the patch should ship it's own updated versions of the campaign maps?

**Comment by MysticaL-AceR** [comment]
I doubt that, although a Revised campaign under development by Goober is still going, doesn't come with Dash, but as a separate mod. It focuses on all stock campaign levels being reworked.

**Comment by tunbridgep** [comment]
I can understand not having any major changes or overhauls, but if this is largely presenting itself as a patch, and there are things in the maps that require new versions to patch, then it makes sense to ship those.

Obviously, this isn't my project so I'll let the developers determine scope, but I don't feel map changes are really that far fetched as long as they are done in the name of bug fixing or changing extremely egregious decisions like the aforementioned labcoat

**Comment by GooberRF** [comment]
I am the Goober that MysticaL-AceR mentioned previously.

I do agree that the behaviour in this section is undesirably punishing, but I also agree with AceR that this is more a map problem than a game problem, so it's probably better solved via a map patch rather than baked into Dash. 

After I read your issue, I prepared such a map patch if you'd like it. You can find it here: https://www.factionfiles.com/ff.php?action=file&id=5918

PS. Just to note - this was the case in the base game, not an issue introduced by Dash.

**Comment by tunbridgep** [comment]
Thank you very much @GooberRF  for the change!

While we're on the subject, are there any other parts of the game you feel are badly designed and should be fixed as part of a "map patch"? I believe that is a project that would be worth pursuing.

I guess this is technically solved now, I will close this issue.

**Comment by tunbridgep** [comment]
Thanks for the invite, I have joined your discord.

I don't know much about the RF Revised project, but the idea behind this would be to create a map patch that is authentic to the original game, something suitable for new players on their first playthrough - no overhauls, no major changes, just bug fixes and fixing things that make sense without any major map additions and changes.

I understand if that's too much of a problem though, you'd probably want to build RF Revised on top of the map patch, to port over the bug fixes, however you've probably already started, which might be a problem.
