### ISSUE TITLE
Suggestion (if feasible): Keep UV mapping when importing mesh brush (Dash RED)

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#17]
Currently, when importing a mesh brush, UV mapping is all removed and the brush is imported with no texture applied. If UVs could be maintained, this would greatly improve the usefulness of mesh brush importing, as it would allow mappers to import geometry directly from 3D software (via v3d tool) including texture mapping.

This may be way too much work than its worth, I honestly don't know. It's not the most critical thing by any means, but it would be a great enhancement to the mapping workflow that I am sure would be used frequently by mappers.

Alternatively, if importing of an additional mesh type (gltf maybe? or obj?) into RED as a brush would be more feasible, that would work too. That route may also provide a workaround to some of the v3d format limitations, and could in theory allow a mapper to design a level mostly in 3D software using the tools in that software package before importing to RED.

**Comment by rafalh** [comment]
Another way to improve import user experience would be to create a tool that can convert gltf to RED group files - format is already reverse engineered. Also it may be better because of higher vertex/triangle limits.
