### ISSUE TITLE
Crash in TheCurseOfOrion TC mod when saving (including autosave)

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#178]
To reproduce:
1. Install mod: https://www.factionfiles.com/ff.php?action=file&id=6100
2. Launch mod and start new SP game
3. Hit button labeled 13 to go to level 13
4. Save the game to crash, or, if you have autosave enabled, crash occurs when the level loads

Level that crashes is c1a2.rfl. Crash log displays this:
> [   4.94] INFO: Level loaded: train01.rfl
> [   5.00] INFO: Prevented rendering of an unlit face with multi-texturing render state
> [   9.20] INFO: Loading level: c1a2.rfl
> [   9.28] INFO: Level loaded: c1a2.rfl (transition)
> [   9.28] INFO: Performing autosave
> [   9.28] WARN: Save file is corrupted: expected up to 64 entities but got 221
> [   9.28] WARN: Save file is corrupted: expected up to 32 deleted events but got 255

I'm guessing this crash is due to the level far exceeding one or more savegame file limits, but still if there were a way to handle this by simply not creating the savegame file rather than crashing, that would be ideal.

**Comment by MartianMadman** [comment]
Just close this you've already banned me from the community lol. Why even bother with this anymore? I'm never going to produce  more content again.

**Comment by MartianMadman** [comment]
There is a difference between wanted your account deleted and banned. I insisted way more on deleting than ban lol. Besides that even if the crashing is fixed a ton of entities and even objects won't be included in the save file.

**Comment by GooberRF** [comment]
> even if the crashing is fixed a ton of entities and even objects won't be included in the save file.
This is true cases where the map exceeds the limits of the savegame format, but a request to raise those limits should be submitted in an issue separate from this one.

**Comment by MartianMadman** [comment]
I already told you that I have already summited an issue about save file limits raising limits before.[https://github.com/rafalh/dashfaction/issues/155](url) I'm getting so tired of having to often repeat myself. At this point I really don't plan on making rf1 content anymore so why are we bothering with these issues that only benefit me.

**Comment by GooberRF** [comment]
I apologize for being unclear - I didn't mean to tell you to submit a request to raise those limits, or give the impression that it would happen if you did. I'm not the owner of the repo, and I don't decide which issues are worth rafalh spending his time on. I get the impression from his reply though that it wouldn't be a small undertaking, and I personally lack the knowledge required to tackle it myself and submit as a PR, so there really isn't anything I can do to help you on that.

All I meant to say was that if you think the limits should be raised, that's a separate issue to this one, which is specifically regarding a crash that occurs consistently when using the save game function on this level. If it were possible to prevent the crash, that would be ideal, and the crash is the only thing this issue is referencing, nothing else.

**Comment by MartianMadman** [comment]
Yes I'll continue to email you so you can ignore me lmao.
