### ISSUE TITLE
Using custom resolutions with fullscreen mode crashes the game at launch

### ISSUE THREAD

**Issue by Mystyled** [rafalh/dashfaction#180]
If fullscreen mode is enabled and the game resolution is set to any value that does not appear in the resolution drop down menu in the Dash launcher, the game will crash upon launch with this error:

<img src="https://user-images.githubusercontent.com/89315313/175972948-f325a8fc-0ee0-4839-94c3-b6f9c471134e.png" width=300 height=auto>

This does not appear to happen if the game is launched in windowed or stretched mode.

Some custom resolutions I tested with:
720x576
960x720
1366x1080
1440x1080
1919x1080

**Comment by rafalh** [comment]
That's DirectX/graphics card driver limitation. What do you except to happen? 
Custom resolutions were supposed to be advanced tool and I suggest not using them with fullscreen.
Perhaps error message could be better and launcher could stop you from configuring wrong resolution. Another option would be to fallback to a valid resolution on game start.
