### ISSUE TITLE
Suggestion: Increase rendering cache size limit

### ISSUE THREAD

**Issue by AtifArshad1995** [rafalh/dashfaction#188]
Right now, the rendering cache cannot be set to higher than 32 MB. This is good enough for almost every map so far, but for future proofing, I would suggest to have the limit increased to something like 128 MB.

For example, there are some very detailed maps (like [DM-Airship](https://www.factionfiles.com/ff.php?action=file&id=5176) ), where I used to get micro stuttering when I had the rendering cache set to 16 MB before I increased it to 32 MB.

**Comment by rafalh** [comment]
`DM Airship(1.2).rfl` uses 672 KB of the geometry rendering cache. I don't experience any difference with cache size set to 16 and 32 MB. I was considering to change the limit in the past but I've never found a map that could come close to 32 MB. 
Please note that increasing this cache size decreases amount of memory for other things like textures and lack of space for textures is already a problem for some people. There is only 2 GB of available RAM and fragmentation makes it even worse to allocate such huge blocks of memory. So I think in the best interest of everyone is to keep the current limit unchanged.
