### ISSUE TITLE
Unknown regression causes game crash

### ISSUE THREAD

**Issue by MartianMadman** [rafalh/dashfaction#194]
The 1st level of my mod (https://www.factionfiles.com/ff.php?action=file&id=6124) crashes upon loading with latest source code build. It however does not crash with with the 1.7.0 build.

**Comment by rafalh** [comment]
Doesn't crash for me

**Comment by MartianMadman** [comment]
This is the same build process you use correct?
![image](https://user-images.githubusercontent.com/89256728/181649871-64c509cf-c376-4052-8a77-976f51baa6ff.png)

**Comment by MartianMadman** [comment]
This is the crash report I get from the build.
[DashFaction-crash.zip](https://github.com/rafalh/dashfaction/files/9214678/DashFaction-crash.zip)

**Comment by MartianMadman** [comment]
> It doesn't crash for me

Maybe your thinking the room with all the numbers and buttons is what I'm talking about? The map is titled c0a0.rfl in the .vpp and utilized by button 1.

**Comment by rafalh** [comment]
Oh, you did not mention that it's a debug build type (`-DCMAKE_BUILD_TYPE=Debug`). `Release` build type does not crash and that's the one that is used for officially released binaries. I reproduced the problem and will take a look.

**Comment by rafalh** [comment]
Hm, I think you have too many waypoint lists - limit is 32. It is causing a memory corruption and I would recommend to reduce it even if it does not crash in release build

**Comment by MartianMadman** [comment]
I do not know how to remove waypoint lists.

**Comment by MartianMadman** [comment]
I put the level into a .rfg group and loaded it to a new level to fix the problem.

**Comment by rafalh** [comment]
Actually I was wrong. The crash happened because you had too many waypoint list nodes: 132 but only 128 are allowed.

**Comment by rafalh** [comment]
Commit 7cfbf5f43c15cf1e02f848d39496f52586f02404 partially fixes the issue and crash is not observed anymore

**Comment by MartianMadman** [comment]
> 

I don't understand what the waypoint list nodes are. Are they the nav points themselves?

**Comment by rafalh** [comment]
Waypoint list consists of navpoints. You can see them after pressing CTRL+W in the editor when nothing is selected.
