### ISSUE TITLE
Alpha sorting regression

### ISSUE THREAD

**Issue by MartianMadman** [rafalh/dashfaction#211]
Dash Faction 1.8.0 has an alpha sorting issue in which Pure Faction or Dash Faction 1.7.0 does not have.
![bug001](https://user-images.githubusercontent.com/89256728/194757532-eabbcffa-d80e-4ae4-bf4d-568c1974d4c2.jpeg)

**Comment by MartianMadman** [comment]
This issue is caused by commit https://github.com/rafalh/dashfaction/commit/2362004a716ac5795eee7b91f3c710fbac3bafbf

**Comment by MartianMadman** [comment]
![20530_2022110121](https://user-images.githubusercontent.com/89256728/199383175-e5ca3370-f648-4a17-bb8c-91e71169b80b.jpg)
Same commit causes this as well.

**Comment by rafalh** [comment]
What map is this?

**Comment by MartianMadman** [comment]
They are from my trashy campaign mod. First image is map c1a8.rfl. Second image is map c1a5.rfl. This issue can be found in base rf campaign, level l5s3 has it.

**Comment by rafalh** [comment]
I've tested L5S3 and it looks fine now. @MartianMadman could you test your campaign?

**Comment by MartianMadman** [comment]
objects are fine now but yellow bullet tracers are rendered below water even though they are above.

**Comment by MartianMadman** [comment]
it renders right in 1.7.0 and 1.8.0

**Comment by rafalh** [comment]
L5S3? Could you make a screenshot? I've tested L10S4 but didn't notice anything

**Comment by MartianMadman** [comment]
It's in modded rf, in Madmod weapons fire tracers and they are being rendered as below water.
![vlcsnap-2024-08-19-12h24m17s276](https://github.com/user-attachments/assets/5d9316bc-5df2-42df-bf39-66f53d0b83e5)

**Comment by rafalh** [comment]
![image](https://github.com/user-attachments/assets/89d8a852-6918-4cba-9a90-4602dde76dc7)
they dont render as underwater for me :o
are you using latest build from master?

**Comment by MartianMadman** [comment]
Pretty sure yes.
