### ISSUE TITLE
RED Editor maximise view port crash

### ISSUE THREAD

**Issue by BATEMAN87** [rafalh/dashfaction#218]
This is a request to fix crashing issue of RED Editor 
When maximising view port "Front" (bottom right) with the hot key F4 the editor crashes, all other view ports behave normal.

**Comment by GooberRF** [comment]
To add to this issue, it is specific to Dash RED (not present in stock RED). This is detailed in issue #117

**Comment by rafalh** [comment]
Closing as a duplicate
