### ISSUE TITLE
Win9x support

### ISSUE THREAD

**Issue by kentonbmax** [rafalh/dashfaction#227]
Hi could you build me a win9x version? Having input freezing issues on my windows 98 SE gaming build. If not could you provide instructions on how I could build my own? Thank you kindly.

**Comment by rafalh** [comment]
Sorry. Dash Faction supports Windows 7 and newer. Windows 98 is 26 year old and hard to support now. I recommend using unmodified game on such an old system (preferably without Internet connection because unmodified RF has some security holes and the system probably does too)
