### ISSUE TITLE
Widescreen Fix for Driller's Cockpit Windshield

### ISSUE THREAD

**Issue by MysticaL-AceR** [rafalh/dashfaction#231]
As you know, the first-person view for the driller vehicle's cockpit is still set to 4:3 by default and heavily coded. Which makes the driller blades be seen outside the designed square-like windshield.

Can it be stretched to 16:9 please?

**Comment by rafalh** [comment]
Adding a screenshot of driller cockpit for reference:
![driller-old](https://github.com/rafalh/dashfaction/assets/160391/3c62bd08-3d3a-4b27-a682-d5cd0a5afb90)
I agree it should be fixed... I tried to scale all cockpits at once but I'm not sure if I like the result. 
[cockpit-widescreen.zip](https://github.com/rafalh/dashfaction/files/14398601/cockpit-widescreen.zip)
Some have reticle included (e.g. fighter) and it looks too stretched. On the other hand it seems to fix some cockpit holes in submarine. It may also be closer to the game developers intentions (hiding details of cockpits that were not visible in the original game).
What do you think?

**Comment by MysticaL-AceR** [comment]
i like the "driller new" picture there! That should be the only fix that's needed in this case, please. The rest of the pictures as in "old" to other vehicles looks okay to me, they don't need fix.

**Comment by rafalh** [comment]
Goober had the same opinion. I changed only the driller cockpit.
