### ISSUE TITLE
Disable rendering the flag of the flag carrier when they're being spectated in first person.

### ISSUE THREAD

**Issue by nickalreadyinuse** [rafalh/dashfaction#24]
Currently, when first person spectating a player that is holding a flag the flag will appear in the camera which obstructs view of the screen almost completely. If possible, de-rendering the flag while viewing that player would resolve this.

**Comment by rafalh** [comment]
I am pretty sure, it used to work in the past...

**Comment by rafalh** [comment]
Actually it seems it never worked. Maybe I just planned to do it and forgot...
