### ISSUE TITLE
Client variable to disable spectator help text

### ISSUE THREAD

**Issue by nickalreadyinuse** [rafalh/dashfaction#25]
Currently, while spectating, the help text explaining the controls is always displayed. This client variable would turn off the help text for a cleaner look.

**Comment by rafalh** [comment]
I moved and shortened the text. Do you think this issue is still relevant after those changes?

**Comment by rafalh** [comment]
![image](https://user-images.githubusercontent.com/160391/114271374-4bb1d800-9a11-11eb-8515-3af19f7827b0.png)
