### ISSUE TITLE
d3d11 bugged custom menu background

### ISSUE THREAD

**Issue by MartianMadman** [rafalh/dashfaction#262]
Aquest menu
![11382118162880266240_20240901164324_1](https://github.com/user-attachments/assets/1974cf43-0521-457b-b636-57a8763e8985)

**Comment by rafalh** [comment]
What's the resolution of that image? Where can I find it?

**Comment by MartianMadman** [comment]
320x240

**Comment by GooberRF** [comment]
> What's the resolution of that image? Where can I find it?
It's in this mod: https://www.factionfiles.com/ff.php?action=file&id=5175

**Comment by rafalh** [comment]
> > What's the resolution of that image? Where can I find it?
> > It's in this mod: https://www.factionfiles.com/ff.php?action=file&id=5175
> 
> EDIT: Also, this bug is very similar to #113, just mentioning that in case it's useful in fixing this one :)

Thanks Goober for mentioning it, that was the same bug :)
