### ISSUE TITLE
DX11 - Entity meshes fade sometimes

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#272]
To replicate:
- Enable DX11
- Load L3S1 (or any other map - this was what I used in my example below)
- Start killing enemies

Entity meshes, and some amount of other meshes (like some light fixtures, shown in the example), fade in and out of existence occasionally. I wasn't able to nail down a specific cause, but given the fade is the same as what happens when corpses fade out and are removed, I'm _thinking_ it's related to that functionality? Perhaps a single buffer being used for all of them, so whenever one starts to fade, they all do? (speculation)

Example video: https://www.youtube.com/watch?v=tjgPF10E6LY

**Comment by rafalh** [comment]
Cannot reproduce...
