### ISSUE TITLE
In team modes, arm color in first person spectate mode isn't consistent with the team of the player being spectated

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#33]
As shown in the screenshot below (courtesy of BATEMAN), when in first person spectate in team modes, the color of the arm reflects the team you are on, rather than the team of the player you're spectating. In this screenshot, BATEMAN is on the red team (but not spawned). He's spectating me, I'm on the blue team, but his spectate view is showing my arm color as red.

![image](https://user-images.githubusercontent.com/17713962/102354045-956b4400-3f84-11eb-80ae-0cb6a5558589.png)

**Comment by rafalh** [comment]
I think 1st person arm/hand model always use current player skin. I consider it enhancement as it never worked differently.
