### ISSUE TITLE
Add missing texture mtl_archway04-mip.tga for mip level 1 on Dbl Flourescent clutter object

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#35]
Include the tga in this zip in dashfaction.vpp, to resolve the missing texture on mip level 1 for the Dbl Flourescent clutter object
[mtl_archway04-mip1.zip](https://github.com/rafalh/dashfaction/files/5710907/mtl_archway04-mip1.zip)

Before and after screenshots:
![1217_screen003](https://user-images.githubusercontent.com/17713962/102517272-69c28980-406a-11eb-91db-eccb0bbd4632.jpg)
![1217_screen004](https://user-images.githubusercontent.com/17713962/102517277-6b8c4d00-406a-11eb-9e30-4e9d3c9d088b.jpg)

**Comment by rafalh** [comment]
Fixed in commit 85e37413d707de27ad03c47797a3eb62beb58dae
