### ISSUE TITLE
Add missing assets for 7 stock RF clutter objects

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#38]
I'm not 100% sure if you want to add these, but given it's only 49KB of added filesize (zipped), I think it would be a good idea.

Adding these files to dashfaction.vpp would allow usage of the below 7 clutter objects by mappers in Dash RED. These are clutter objects listed and configured in the stock clutter.tbl file, but missing assets in the released game from Volition, meaning they don't appear in the editor and are therefore unusable by mappers. This .zip contains the original models, extracted from one of the ps2 demo versions (and then ccrunched), plus textures for the models.

[7clutter.zip](https://github.com/rafalh/dashfaction/files/5716056/7clutter.zip)

I don't think adding all of the cut textures to Dash is worth the filesize (mappers can just download those from FF and load them as custom textures), but given these clutter objects are already configured and referenced in the stock table files, and the filesize impact is so low, I think they're worth including.

Fixed clutter objects are:
Oil Drum Fire
Spotlight02
icicle1
icicle2
icicle3
icicle4
icicle5

**Comment by rafalh** [comment]
I'm not sure if we should add them if the stock game does not used them. They would only help mappers in new maps but also make those maps incompatible with other clients. Mappers can include those meshes themselves in maps and maybe some do? They could even be used as alternative to Switch_Model if Dash allowed multiple vpps to have files with the same name and deciding which one to use based on loaded map. So maybe it's better to not rush anything here.

**Comment by GooberRF** [comment]
I agree, this shouldn't be actioned. The assets are available for anyone who wishes to use them (as some maps have already), which is a better approach than is suggested in this issue.
