### ISSUE TITLE
Add cVar to change FOV manually

### ISSUE THREAD

**Issue by Keith94** [rafalh/dashfaction#45]
Useful for people who don't like the default FOV.

**Comment by rafalh** [comment]
I think it can be implemented but some reasonable range should be set to prevent people from breaking the game. I think range 60-135 would make sense.

**Comment by rafalh** [comment]
Actual FOV range is 75-120. Above 120 first person gun models are having problems.

**Comment by Keith94** [comment]
Excellent; thanks for adding it!
