### ISSUE TITLE
Suggestion: Method to stop rendering specific meshes when they're far away from the camera

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#49]
Would be ideal to give level/mod designers a way to specify certain meshes (primarily clutter objects) to stop rendering after X metres. This would allow designers heavily enhanced ability to add detail to levels without impacting performance. Lots of other games have similar functionality for this purpose. A simple example would be a house with clutter (plates, cups, etc.) on a table, or a shelf in a corner of a room. If the player is looking at that house from 50m away, the level designer could decide that there's no need to render the plates/cups/shelves in that room, even if the room is visible through a window (that has a portal). Derendering such objects when the player is far away would allow designers to create and optimize levels with a much higher level of detail than is currently possible in the engine.

I'm not sure the best way to implement this though - maybe a mapname_cfg.tbl file that could be included with maps that specifies settings for specific clutter object classes? You could also leverage this mapname_cfg.tbl file in the future, if you decide to implement other configurable settings like this for maps.

Example:
dm02_cfg.tbl could contain:

$Clutter Draw Distance: "bench01" 10

And that would make any instances of bench01 in dm02 to not render unless the camera was <10m away from the object. Alternatively, it might be an even better idea to specify objects by UID rather than class, to allow designers to specify different values for objects in different areas of the level. (for example, the benches in one area maybe should be visible from a further distance than the benches in a different area) The UID approach would offer far more flexibility and potential for optimization, but I'm not sure how complex it would be to implement.

If you wanted to, you could also include a cvar for clients to adjust this behaviour to improve performance. Perhaps the default behaviour could be to obey exactly the settings in mapname_cfg.tbl, but a cvar could allow players to set a multiplier for those values? 

As an example, building on my above example, if the client specified "draw_distance_multiplier 0.5", a 0.5 multiplier would be applied to the configured value for bench01 in mapname_cfg.tbl - so bench01 would not render unless the camera was <5m away from it.

**Comment by rafalh** [comment]
LOD meshes exists just for that, to reduce amount of rendering in a distance. Currently most players do not use LOD meshes at all ("Disable LOD models" option in DF). It would make more sense to keep that feature but multiply LOD distances by some factor or disable them only for vanilla game models. I'm not sure allowing to cancel rendering entirely is that good idea. Properly portaled level  shouldn't render a lot of occluded objects. Keep in mind that portals not only makes some room to not render at all but also are used by the engine to determine what part of the room is visible. E.g. in case of a home interior visible from the outside only objects that are visible through the window would be rendered (bounding frame of the portal is used to determine part of screen that needs to be updated).
As a hackish solution to this problem (if LOD models were enabled) would be to make a LOD mesh that has 0 vertices.

**Comment by GooberRF** [comment]
Closing issue because this capability is already available (albeit "hackish") if a designer wishes to avail of it. Adding as a feature isn't necessary if designers properly optimize their levels.
