### ISSUE TITLE
RED crashes when changing properties of faces with different lightmap resolution

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#50]
To replicate:

-Open Dash RED
-Make 4x4x4 cube
-Go to texture mode
-Select 2 faces, properties, set to highest lightmap resolution, hit OK
-Select all faces in cube, properties, tick smoothing group 1, hit OK
-Build geometry
-Crash

**Comment by rafalh** [comment]
Does it happen in vanilla RED?

**Comment by GooberRF** [comment]
> Does it happen in vanilla RED?

Sorry, forgot to mention that. Yes, it does.

**Comment by rafalh** [comment]
I did some testing and smoothing group selection is redundant - crash happens even if you don't change anything in face properties window and just click OK (and build then)...
