### ISSUE TITLE
levelsounds not functional in 1.6.0

### ISSUE THREAD

**Issue by nickalreadyinuse** [rafalh/dashfaction#51]
Potential regression from 1.5.0, levelsounds command is no longer functional - cannot mute ambient audio sources in maps, particularly music / annoyances.

**Comment by rafalh** [comment]
After initial analysis there are two conclusions:
* ambient sounds are broken in 1.6.0 if EAX sounds are disabled
* sounds emmited by movers (e.g. in dm-ccp) were never not supported by `levelsounds`
