### ISSUE TITLE
Suppress editor prompt when saving advising of > 64 decals

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#61]
![image](https://user-images.githubusercontent.com/17713962/105618815-317b3d00-5dc6-11eb-9d30-3ff7d1649cf2.png)
This is the prompt, received when saving a map with >64 decals in it.

Easiest way to receive the prompt is to open dm12 in editor and resave it

**Comment by rafalh** [comment]
After 0672f1c523baf11f5a76c382d58659be224c9447 Dash Editor will display the warning after creating 127 decals instead of 64.
