### ISSUE TITLE
DF server variable to enable max ammo on pickup

### ISSUE THREAD

**Issue by nickalreadyinuse** [rafalh/dashfaction#66]
Primarily for use in large public servers so that players can get ammo from weapons while WS is enabled.

**Comment by rafalh** [comment]
How is it supposed to work? Item pickup should give max ammo?

**Comment by nickalreadyinuse** [comment]
Yeah, that would be a more elegant solution I think. I had something else in mind but max ammo on pickup would suffice (except for Fusion which should be excluded).
