### ISSUE TITLE
CTF flag spins (as if dropped) when on base if it was dropped at end of last match

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#74]
If a CTF flag is dropped (waiting to be returned), it spins. If the flag is dropped and spinning when the level ends, that flag will be spinning on its base in the next level until its picked up and returned.

To replicate:
1. Steal flag
2. Kill self with kill command (flag is now dropped and spinning)
3. Switch to next map
4. Observe, the flag you stole before and dropped is now spinning on its flag base in the newly loaded level

**Comment by rafalh** [comment]
Wow, I've never see it happen. Is it a regression? Can you pickup that duplicated flag in the next level?

**Comment by GooberRF** [comment]
Picking it up works find, as far as I can tell it's strictly a visual bug.

I haven't specifically tested other versions, but I do remember seeing flags spinning on their base in PF throughout the years, so I expect it's an RF bug rather than a DF bug. Will confirm.
