### ISSUE TITLE
Game shows critical error when loading a savegame file that was created when player was out of the level

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#84]
Often encountered in speedruns (accidentally), but also could be potentially encountered in limited circumstances on normal playthroughs. 

I wouldn't expect loading these savegame files to load properly, but perhaps Dash could refuse to load the savegame file and either print an error to the console or present an error message on-screen, when attempting to load such savegame files, rather than crashing? Seems like that would be less abrupt for players, and wouldn't cause them to lose their progress.

As an example, I've attached a savegame file created while the player is out of the level in L12S1.rfl (just flew up over the canyon via heehoo). This savegame file will crash the game when you load it.

[L12S1_crash.zip](https://github.com/rafalh/dashfaction/files/5988890/L12S1_crash.zip)

**Comment by rafalh** [comment]
It is not a crash, it's a fatal error - message box that shows "Failure to create player  entity" message and then kills the game.
It is nothing new and happens mostly for speed runners so it's on very low priority.

**Comment by rafalh** [comment]
Possible ways to improve situation:
* disallow saving outside of the level
* show error when loading save file without killing the game
* allow spawning player entity outside the level

**Comment by GooberRF** [comment]
allow spawning player entity outside the level

If it's feasible, this would be the best improvement in my mind. It wouldn't be jarring for normal players (they'd never even notice a difference in behaviour between saving outside/inside the level) - the only people who would even notice that spawning player entity outside the level works now are the speedrunners, and it would be an improvement for them.

**Comment by GooberRF** [comment]
Completed
