### ISSUE TITLE
Wrong font charset for big HUD and main menu

### ISSUE THREAD

**Issue by token0** [rafalh/dashfaction#92]
Cyrillic font charset in big HUD mode is wrong. This applies to main menu and in-game. Charset is correct in small HUD mode.
Tested in both latest release and latest beta.

![big hud = broken charset](https://user-images.githubusercontent.com/4627595/109388873-64a77380-7912-11eb-95ce-73c887ec04e7.png)
![small hud = correct charset](https://user-images.githubusercontent.com/4627595/109388878-6a04be00-7912-11eb-8dff-9e8f7660f3e0.png)

**Comment by GooberRF** [comment]
If my memory is correct, this may be because the unofficial Russian conversions reuse the ANSI character codes for the English characters but replace them with cyrillic characters - at least it was that way in the Russian conversion I used, but I think there are multiple different Russian conversions.

**Comment by token0** [comment]
@GooberRF , on the first screenshot is not the char substitution (I know how does it look like). Usually this issue (on 1st screenshot) appears when current font does not have Cyrillic characters, [and/or] code page of application is not 1251 (which is used in particular localization), so if falls back to 1250 or 1252 (Latin).

[Here's the article about 125x code pages in Windows](https://en.wikipedia.org/wiki/Windows_code_page#Windows-125x_series)
Please, compare Latin character sets [1250](https://en.wikipedia.org/wiki/Windows-1250), [1252](https://en.wikipedia.org/wiki/Windows-1252) with Cyrillic [1251](https://en.wikipedia.org/wiki/Windows-1251). As you can see, only 1251 has needed (Cyrillic) symbols, and 1250 and 1252 are just the thing from first screenshot.

Chosen OptiEdgar font does not have Cyrillic characters at all, so it falls back to Latin ones. 
[Here's the example:](https://www.ffonts.net/OPTIEdgar-Extended.font?text=OptiEdgar+%D0%BD%D0%B5+%D0%B8%D0%BC%D0%B5%D0%B5%D1%82+%D0%BA%D0%B8%D1%80%D0%B8%D0%BB%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85+%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%B2+%3B+OptiEdgar+doesn%27t+have+Cyrillic+symbols)
![image](https://user-images.githubusercontent.com/4627595/109628239-319bf480-7b4b-11eb-910b-6840f1238bca.png)

In the ideal world we should have Unicode with universal fonts with all characters. 

In this particular case (in the DashFaction) would be good to have any fallback font with Cyrillic chars, or ability to substitute with or choose own font in the configurator. 

PS: I did not have success of building DashFaction to experiment with fixing this issue. Tried Cmake, VS2019, Code Blocks, Linux, etc… Could somebody share a working project file or working configuration?

**Comment by rafalh** [comment]
It's not just a font problem. RF uses Windows-1252 encoding and it's not like DF can change that without breaking existing translations. Sure, unicode would be cool but it's not as easy as changing a font. It requires changes to the code. And it won't really fix existing Russian translation packs which just reuse some characters of windows-1252 encoding for their own purpose. Optimally tables and network protocol should support utf-8 but it is a non-trivial change and is not backward compatible.
@token0 I wonder what is your problem with building the project. Building process is as simple as possible with CMake... If you have compiler errors maybe you are using some ancient compiler. MSVC 2017 and MinGW 9+ should work just fine.

**Comment by token0** [comment]
@rafalh  I succeed building DF on my Linux machine just yesterday, without any IDE, just cmake and make. 
I've made this localization working! 
It is just 1251 (which has both English and Cyrilic glyphs) and does not have any substitutions.
Please take a look here https://github.com/token0/dashfaction/commit/8f71e26da572a0730f6cd65fc96cb5e2b3f0ab0f

![image](https://user-images.githubusercontent.com/4627595/110540915-bf6d7600-812f-11eb-9ec5-4587cd6afef4.png)

**Comment by rafalh** [comment]
Looks cool. But it's not something I could upstream in such form. As I see it russian language pack could include custom fonts. But as I've seen in your change you also changed the list of characters that are rendered into font atlas. I'm not sure what is the best way to change it. Current list is based on characters that original RF fonts had defined (most have empty glyphs except ASCII). But in case of translations it makes sense to use different codepoints e.g. like you used a different encoding than what RF uses. Maybe some tbl file with configuration of glyphs mapping would be a good direction. Language packs would include fonts + tbl file with glyphs config + strings.tbl.

**Comment by rafalh** [comment]
I fixed main menu. In game fonts should be okay if you disable Big HUD.
