### ISSUE TITLE
Entities pass through level loads, but are not maintained if the player backtracks into a previous level

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#99]
Example from custom campaign: https://youtu.be/Vkhvd1eGLQk
Example from stock game: https://youtu.be/nSqJaPwcVcg

Stock game example is from the L2S3->L3S1 transition.

**Comment by rafalh** [comment]
As far as I know only entities that are in the same room as the player are kept during level transition. I don't think it matters if it is a transition to the next level or the previous.

**Comment by GooberRF** [comment]
Ahh ok, now that you mention that, it does make sense. In the custom campaign, I had a portal on the metal frame in the middle of the hallway - when I remove that portal, he comes back and forth fine between level loads.

Is it maybe possible to change the functionality so it brings entities back/forth in level loads if they're in a rendered room, rather than only the room the player is in? In theory I think that would stop entities from disappearing (unless they're off-screen anyway, in which case you'd never miss them).
